---
name: Build and Push Golang Image to AWS ECR
on:
  push:
    tags:
      - rc* 

jobs:
  build:
    name: Build an image

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Get the version
      run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

    - name: Build image and push to registry
      run: |
        aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 353918212181.dkr.ecr.us-west-1.amazonaws.com
        docker build -t meteor .
        docker tag meteor:latest 353918212181.dkr.ecr.us-west-1.amazonaws.com/meteor:$SOURCE_TAG
        docker push 353918212181.dkr.ecr.us-west-1.amazonaws.com/meteor:$SOURCE_TAG
